#' Computes a transform using the 'logicle_transform' function but keeping zero
#' at zero
#'
#'
#' The default logicle transformation transforms the zero intensity into a value
#' that is not zero. The current transformation removes this offset after the
#' standard logicle transformation in order to keep zero at zero. See Logicle
#' transformation \code{\link{logicleTransform}} for all parameters.
#'
#' The estimateLogicle function estimates the parameter w (width of the linear
#' zone) from the negative (left) part of a marker's negative peak. It
#' calculates the 5th percentile of intensities below the zero threshold. The
#' estimateLogicleZ function defines the center of the negative peak and
#' subtracts this value from all intensities before performing the classic
#' estimate.
#'
#'
#' @aliases logicleZTransform estimateLogicleZ
#' @usage logicleZTransform(transformationId="defaultLogicleTransform", w = 0.5,
#'   t = 262144, m = 4.5, a = 0)
#' @usage estimateLogicle(x, channels,...)
#' @param transformationId A name to assign to the transformation. Used by the
#'   transform/filter routines.
#' @param w w of logicleTransform.
#' @param t t of logicleTransform.
#' @param m m of logicleTransform.
#' @param a a of logicleTransform.
#' @param z logical bring back zero at zero.
#' @param n negative intensity threshold.
#' @param x Input flow frame for which the logicle transformations are to be
#'   estimated.
#' @param channels channels or markers for which the logicle transformation is
#'   to be estimated.
#' @param ... other arguments:
#'
#'   q: a numeric type specifying quantile value, default is 0.05
#' @seealso \code{\link[flowCore]{inverseLogicleZTransform}},
#'   \code{\link[flowCore]{estimateLogicle} }
#' @references Parks D.R., Roederer M., Moore W.A.(2006) A new "logicle" display
#'   method avoids deceptive effects of logarithmic scaling for low signals and
#'   compensated data. CytometryA, 96(6):541-51.
#' @keywords methods
#' @examples
#'
#' # GvHD is not a recent dataset to show the interest of this transformation
#'
#' @export
logicleZTransform <- function(
    transformationId="defaultLogicleZTransform",
    w = 0.5, t = 262144, m = 4.5, a = 0, z = TRUE, n = 0) {

  k <- new("transform", .Data = function(x) {
    if (n != 0) x <- x - n
    x <- logicle_transform(as.double(x), as.double(t), as.double(w), as.double(m), as.double(a), FALSE)
    if (z) x <- x - w
  })
  k@transformationId <- transformationId
  k
}
#' @export
estimateLogicleZ <- function(x, channels, ...) UseMethod("estimateLogicleZ")
#' @export
estimateLogicleZ.flowFrame <- function(x, channels, ...){
  trans <- .estimateLogicleZ(x, channels, ...)
  channels <- names(trans)
  transformList(channels, trans)
}
.estimateLogicleZ <- function(x, channels,...){
  if(!is(x,"flowFrame")&&!is(x,"cytoframe"))
    stop("x has to be an object of class \"flowFrame\"")
  if(missing(channels))
    stop("Please specify the channels to be logicle transformed");
  channels <- sapply(channels, function(channel)
    getChannelMarker(x, channel)[["name"]], USE.NAMES = FALSE)

  sapply(channels, function(p) {
    .lgclZTrans(x, p, ...)
  })
}
#' It is mainly trying to estimate w (linearization width in asymptotic decades)
#' value based on given m and data range
#' @param obj flowFrame
#' @param p channel name
#' @param m full length of transformed display in decodes
#' @param t top of the scale of data value
#' @param a additional negative range to be included in display in decades
#' @param q quantile of negative data value (used to adjust w calculation)
#' @param type character either "instrument" or "data". The data range.
#' @param z logical bring back zero at zero
#' @param n negative intensity threshold or intensity of the zero
#' @noRd
.lgclZTrans  <- function(obj, p, t , m, a = 0, q = 0.05, type = "instrument", z = TRUE, n = 0) {
  type <- match.arg(type, c("instrument", "data"))
  transId <- paste(p,"logicleZTransform", sep = "_")

  rng <- range(obj)
  dat <- exprs(obj)[,p]
  if (n) dat <- dat - n

  if(missing(t)){
    if(type == "instrument")
      t <- rng[,p][2]
    else
      t <- max(dat)
  }

  if(missing(m)){
    if(type == "instrument")
      m <- 4.5 # hard coded value to keep consistency with the legacy behavior
    else
      m <- log10(t) + 1
  }

  dat <- dat[dat<0]
  w <- 0
  if(length(dat)) {
    r <- .Machine$double.eps + quantile(dat, q)
    w=(m-log10(t/abs(r))) / 2
    if(w<0)
      stop("w is negative! Try to increase 'm'")
  }
  logicleZTransform(transformationId = transId, w = w, t = t, m = m, a = a, z = z, n = n)
}


#' Computes the inverse of the transform defined by the 'logicleZTransform'
#' function or the transformList generated by 'estimateLogicleZ' function
#'
#' inverseLogicleTransform can be use to compute the inverse of the Logicle
#' transformation. The parameters w, t, m, a for calculating the inverse are
#' obtained from the 'trans' input passed to the 'inverseLogicleTransform'
#' function. (The inverseLogicleTransform method makes use of the C++
#' implementation of the inverse logicle transform contributed by Wayne Moore
#' et al.)
#'
#' @usage inverseLogicleZTransform(trans,transformationId, ...)
#' @param trans An object of class 'transform' created using the
#' 'logicleZTransform' function or class 'transformList' created by
#' 'estimateLogicleZ'.  The parameters w, t, m, a for calculating the inverse
#' are obtained from the 'trans' input passed to the 'inverseLogicleZTransform'
#' function.
#' @param transformationId A name to assigned to the inverse transformation.
#' Used by the transform routines.
#' @param ...  not used.
#' @seealso \code{\link[flowCore]{logicleZTransform}}
#' @references Parks D.R., Roederer M., Moore W.A.(2006) A new "logicle"
#' display method avoids deceptive effects of logarithmic scaling for low
#' signals and compensated data. CytometryA, 96(6):541-51.
#' @keywords methods
#' @examples
#'
#' # GvHD is not a recent dataset to show the interest of this transformation
#'
#' @export
inverseLogicleZTransform <- function(trans, transformationId, ...)
  UseMethod("inverseLogicleTransform")
#' @export
inverseLogicleZTransform.default <- function(trans, transformationId, ...) {
  stop("trans has to be an object of class \"transform\"
            created using the \"logicleTransform\" function\n
         or a 'transformList' created by 'estimateLogicle'\n")
}
#' @export
inverseLogicleZTransform.transform <- function(trans, transformationId, ...) {
  k <- .inverseLogicleZTransform(trans@.Data)
  if(missing(transformationId))
    k@transformationId <- paste( "inverse", trans@transformationId, sep ="_")
  k
}
.inverseLogicleZTransform <- function(func){
  pars <- c("w", "t", "m", "a", "z", "n")
  vals <- ls(environment(func))
  if(!all(pars %in% vals))
    stop("\"trans\" is not a valid object produced using the
           \"logicle\" function")

  w = environment(func)[["w"]]
  t = environment(func)[["t"]]
  m = environment(func)[["m"]]
  a = environment(func)[["a"]]
  z = environment(func)[["z"]]
  n = environment(func)[["n"]]
  k <- new("transform", .Data=function(x) {
    if (z) x <- x + m
    x <- logicle_transform(as.double(x), as.double(t), as.double(w), as.double(m), as.double(a), TRUE)
    if (n) x <- x + n
  })

}
#' @export
inverseLogicleZTransform.transformList <- function(trans, transformationId, ...) {
  invs <- sapply(trans@transforms, function(obj){
    .inverseLogicleZTransform(obj@f)
  })
  channels <- names(invs)
  if(missing(transformationId))
    transformationId <- paste( "inverse", trans@transformationId, sep ="_")

  transformList(channels, invs, transformationId = transformationId)
}
